export default [
    {
        id: 1,
        name:"Life Lessons with Katie Zaferes",
        img:"/images/life-lessons.png",
        rating:"5.0",
        stock:"6",
        country:"USA",
        price:136,
        openSpots:0,
    },
    {        
        id: 2,
        name:"Learn Wedding Photography",
        img:"/images/wedding-photography.png",
        rating:"5.0",
        stock:"30",
        country:"ITALY",
        price:125,
        openSpots:1,
    },
    {
        id: 3,
        name:"Group Mountain Biking",
        img:"/images/mountain-bike.png",
        rating:"4.8",
        stock:"2",
        country:"NIGERIA",
        price:50,
        openSpots:3,
    },
    {
        id: 4,
        name:"Group Mountain Biking",
        img:"/images/mountain-bike.png",
        rating:"4.8",
        stock:"2",
        country:"NIGERIA",
        price:50,
        openSpots:30,
    }
]